# fly.toml app configuration file generated for gitea-brentgruberorg on 2024-03-21T20:04:06-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gitea-brentgruberorg'
primary_region = 'bos'
kill_timeout = '5s'

[build]
  image = 'gitea/gitea'

[env]
  GITEA__database__DB_TYPE = 'sqlite3'
  GITEA__database__PATH = '/data/gitea/gitea.db'
  GITEA__security__INSTALL_LOCK = 'true'
  GITEA__server__DOMAIN = 'brentgruberorg-gitea.fly.dev'
  GITEA__server__REDIRECT_OTHER_PORT = 'true'
  GITEA__server__ROOT_URL = 'https://brentgruberorg-gitea.fly.dev/'
  GITEA__service__DISABLE_REGISTRATION = 'true'

[[mounts]]
  source = 'gitea_data'
  destination = '/data'

[[services]]
  protocol = 'tcp'
  internal_port = 22

[[services.ports]]
    port = 22

[[services]]
  protocol = 'tcp'
  internal_port = 80

[[services.ports]]
    port = 80
    handlers = ['http']

[[services]]
  protocol = 'tcp'
  internal_port = 3000

[[services.ports]]
    port = 443
    handlers = ['tls', 'http']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
