# fly.toml app configuration file generated for gitea-brentgruberorg-runner on 2024-03-22T22:07:17-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gitea-brentgruberorg-runner'
primary_region = 'bos'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
